title: RSMP Specification
description: >
  RSMP (Road Side Message Protocol) is a standardized protocol for communication
  between supervision systems and road side equipment.
url: "https://rsmp-nordic.github.io/rsmp_core"
github_username: rsmp-nordic
repository: rsmp-nordic/rsmp_core
github: [metadata]

theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

color_scheme: rsmp
logo: "/assets/images/rsmp_logo.png"

mermaid:
  version: "10"
